apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>app3</title>
    </head>
    <body>
        <h1>You are in app3</h1>
    </body>
    </html>
