Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Ubuntu 20.04 LTS

  # Machine Serveur (K3s Server)
  config.vm.define "tsoloherS" do |server|
    server.vm.hostname = "tsoloherS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end

  # Machine Worker (K3s Agent)
  config.vm.define "tsoloherSW" do |worker|
    worker.vm.hostname = "tsoloherSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end
end
