Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64" # Ubuntu 20.04 LTS

  server_ip = "192.168.56.110"
  agent_ip = "192.168.56.111"

  # Machine Serveur (K3s Server)
  config.vm.define "tsoloherS", primary: true do |server|
    server.vm.hostname = "tsoloherS"
    server.vm.network "private_network", ip: server_ip
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "tsoloherS"
    end
    
    # Installation K3s en mode server
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  # Machine Worker (K3s Agent) - démarre après le serveur
  config.vm.define "tsoloherSW" do |worker|
    worker.vm.hostname = "tsoloherSW"
    worker.vm.network "private_network", ip: agent_ip
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "tsoloherSW"
    end
    
    # Installation K3s en mode agent
    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end